/* Generated by vala-dbus-binding-tool. Do not modify! */
/* Generated with: /usr/local/bin/vala-dbus-binding-tool --api-path=/local/pkg/fso/specs/xml/ --directory=./ --strip-namespace=org --rename-namespace=freedesktop:FreeDesktop --rename-namespace=freesmartphone:FreeSmartphone */
using DBus;
using GLib;

namespace FreeSmartphone {

	namespace Data {

		[DBus (name = "org.freesmartphone.Data.World")]
		public interface World : GLib.Object {

			public abstract async WorldBusname[] get_all_countries() throws DBus.Error;

			public abstract async string get_country_code_for_mcc_mnc(string mcc_mnc) throws FreeSmartphone.Error, DBus.Error;
		}

		public struct WorldBusname {
			public string attr1;
			public string attr2;
		}
	}
}
